name: Verify Build Workflow
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [master]
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [master]

jobs:
  build-verify:
    name: Verify Build
    runs-on: ubuntu-latest
    #if: github.repository_owner == 'Apicurio'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64
          
      - name: Login to DockerHub Registry
        if: github.event_name == 'push'
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p "${{ secrets.DOCKERHUB_PASSWORD }}" docker.io
      
      - name: Login to Quay.io Registry
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build Project
        run: mvn clean install      

      #- name: Run Integration Tests
      #  run: mvn install -pl :apicurio-studio-test-integration-arquillian -Pintegration

      # Open-Source Machine emulator that allows you to emulate multiple CPU architectures on your machine
      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v1
        
      # Docker CLI plugin for extended build capabilities with BuildKit
      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Inspect builder
        if: github.event_name == 'push'
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and Publish Studio API
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
         context: ./platforms/thorntail/api
         file: ./platforms/thorntail/api/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: |
           quay.io/rishabprasad005/apicurio-studio-api:latest-snapshot
           quay.io/rishabprasad005/apicurio-studio-api:latest-snapshot

      - name: Build and Publish Studio WS
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
         context: ./platforms/thorntail/ws
         file: ./platforms/thorntail/ws/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: |
           quay.io/rishabprasad005/apicurio-studio-ws:latest-snapshot
           quay.io/rishabprasad005/apicurio-studio-ws:latest-snapshot

      - name: Build and Publish Studio UI
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
         context: ./platforms/thorntail/ui
         file: ./platforms/thorntail/ui/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: |
           quay.io/rishabprasad005/apicurio-studio-ui:latest-snapshot
           quay.io/rishabprasad005/apicurio-studio-ui:latest-snapshot
